POST localhost:8080/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsInJlZ0RhdGUiOiIyMDI1LTAyLTE2VDE3OjI0OjA3LjE4OTQ1MSJ9.eyJ1c2VyTmFtZSI6InRlc3QiLCJ1c2VySWQiOjEsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImV4cCI6MTczOTY5NTQ0N30.1Hwp1pVwey-jP3kp6OvYEXs0i_dMWdsEZes2XPQwJ4A